# Generated by Django 5.0.6 on 2024-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.DateTimeField(auto_now_add=True)),
                ('pname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
